[package]
name = "factor-world"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy_math.workspace = true
redb.workspace = true
thiserror.workspace = true

[dev-dependencies]
approx = "0.5.1"
png = "0.18.0"
rand = "0.8.5"
